generator:
  class: sfDoctrineGenerator
  param:
    model_class:           CatalogueCategory
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          catalogue_category
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    ~
      filter:  ~
      form:    ~
      edit:
        title: Редактирование категории %%name%%
      new:
        title: Новая категория
