generator:
  class: sfDoctrineGenerator
  param:
    model_class:           CatalogueCategory
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          catalogue_category
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        title: Каталог
        table_method: getFullTree
        #max_per_page: 9999
      filter:
        #display: [name]
        class: false
      form:    ~
      edit:    ~
      new:     ~
