default:
  stylesheets:
    - http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/themes/base/jquery-ui.css
  javascripts:
    - http://ajax.googleapis.com/ajax/libs/jquery/1.4/jquery.min.js
    - http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/jquery-ui.min.js
    