generator:
  class: sfDoctrineGenerator
  param:
    model_class:           CatalogueItem
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          catalogue_item
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        title: Test Catalogue
        display: [_preview, =name]
        max_per_page: 2
      filter:
        class: false
      form:    ~
      edit:
        title: Редактирование элемента %%name%%
      new:
        title: Новый элемент
